version: '3'
services:
  webgoat:
    build:
      context: ./webgoat_docker
      dockerfile:  Dockerfile
    image: ${registryUrl}/webgoat:${BUILDFULLNAME}
    tty: true
    ports:
        - "80:80"
    volumes:
      - mydata:/mount/test-volume
volumes:
  mydata:
    driver: azure_file
    driver_opts:
      share_name: myfileshare
      storage_account_name: michaldevopsstorage
