version: '3.1'

services:

  webgoat:
    image: webgoat/webgoat-8.0:v8.0.0.M25
    environment:
      - WEBWOLF_HOST=localhost
      - WEBWOLF_PORT=9090
    ports:
      - "8080:8080"
      - "9001:9001"
    volumes:
      - mydata:/mount/test-volume
